FORMAT: 1A
HOST: http://os-app1-os-app1.193b.starter-ca-central-1.openshiftapps.com/rest/

# osapp1

os-app1 is a RESTful API for the ClassicModels MySQL sample database.

---
## Customers Collection [/customers]
### List all Customers [GET]
Retrieve a list of Customers.

+ Response 200 (application/json)

        [
            
        ]


### Create a Customer [PUT]
+ Request (application/json)

        {
            "fname": "Ram",
            "lname": "Jadhav",
            "email": "ram@email.com"
        }

+ Response 201 (application/json)

        {
            "id": 3,
            "fname": "Ram",
            "lname": "Jadhav",
            "email": "ram@email.com"
        }

## Customer [/customers/{id}]
A single Customer object with all its details

+ Parameters
    + id (required, Number, `1`) ... Numeric `id` of the User to perform action with.

### Retrieve a Customer [GET]
+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "fname": "Pandurang",
                "lname": "Patil",
                "email": "pandurang@email.com"
            }

### Update a Customer [POST]
Update customer details
+ Request (application/json)

        {
            "id": 1,
            "fname": "Pandurang",
            "lname": "Patil",
            "email": "pandurangpatil@email.com"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "fname": "Pandurang",
            "lname": "Patil",
            "email": "pandurangpatil@email.com"
        }

### Remove a Customer [DELETE]
+ Response 204




## Employees Collection [/employees]
### List all Employees [GET]
Retrieve a list of Employees.

+ Response 200 (application/json)

        [
            
        ]
        
        


## Offices Collection [/offices]
### List all Offices [GET]
Retrieve a list of Offices.

+ Response 200 (application/json)

        [
            
        ]
        
        
## Orderdetails Collection [/orderdetails]
### List all Orderdetails [GET]
Retrieve a list of orderdetails.

+ Response 200 (application/json)

        [
            
        ]
        
        
## Orders Collection [/orders]
### List all Orders [GET]
Retrieve a list of Orders.

+ Response 200 (application/json)

        [
            
        ]
        

## Productlines Collection [/productlines]
### List all Productlines [GET]
Retrieve a list of Productlines.

+ Response 200 (application/json)

        [
            
        ]
        

## Products Collection [/products]
### List all Products [GET]
Retrieve a list of Products.

+ Response 200 (application/json)

        [
            
        ]