FORMAT: 1A
HOST: http://os-app1-os-app1.193b.starter-ca-central-1.openshiftapps.com/rest/

# osapp1

os-app1 is a RESTful API for the ClassicModels MySQL sample database.

## Customers Collection [/customers]

### List All Customers [GET]

+ Response 200 (application/json)

        [
            
        ]


### Create a New Customer [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
            }
            
            
## Employees Collection [/employees]

### List All Employees [GET]

+ Response 200 (application/json)

        [
            
        ]
        

## Oficces Collection [/oficces]

### List All Oficces [GET]

+ Response 200 (application/json)

        [
            
        ]
        
        
## Order Details Collection [/orderdetails]

### List All Order Details [GET]

+ Response 200 (application/json)

        [
            
        ]
        
        
## Orders Collection [/orders]

### List All Order Details [GET]

+ Response 200 (application/json)

        [
            
        ]
        
        
## Payments Collection [/payments]

### List All Payments [GET]

+ Response 200 (application/json)

        [
            
        ]
   
        
## Product lines Collection [/productlines]

### List All Product lines [GET]

+ Response 200 (application/json)

        [
            
        ]
   
        
## Products Collection [/products]

### List All Product [GET]

+ Response 200 (application/json)

        [
            
        ]